# Hot-reloading with Air - https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
exclude_dir = ["tmp", "web/static"]
cmd = "cd /app && go build -ldflags='-X main.Tag=v0.0.0' -gcflags='all=-N -l' -o /tmp/main ."
full_bin = "pkill -9 'dlv|main'; sleep 0.1; dlv exec --accept-multiclient --log --headless --continue --listen :2345 --api-version 2 /tmp/main"
include_ext = ["go", "gohtml", "json", "scss"]
include_file = ["main.go"]