version: "3.6"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/sirius-lpa-frontend/Dockerfile
    ports: ["8888:8080"]
    environment:
      SIRIUS_URL: http://sirius-mock:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080

  sirius-mock:
    image: wiremock/wiremock:2.35.0
    ports: ["1234:8080"]
    volumes:
      - "../cypress/mocks:/home/wiremock/mappings"
