version: "3.6"

services:
  app:
    image: sirius-lpa-frontend:latest
    build:
      context: ..
      dockerfile: ./docker/sirius-lpa-frontend/Dockerfile
    depends_on:
      - sirius-mock
    ports: ["8888:8080"]
    environment:
      SIRIUS_URL: http://sirius-mock:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080

  sirius-mock:
    image: wiremock/wiremock:2.35.0
    ports: ["8563:8080"]
    volumes:
      - "../cypress/mocks:/home/wiremock/mappings"

  puppeteer:
    build: ./puppeteer
    depends_on:
      - app
    environment:
      - LHCI_BUILD_CONTEXT__CURRENT_HASH=$GITHUB_SHA
      - LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG=ministryofjustice/opg-sirius-lpa-frontend
      - LHCI_GITHUB_APP_TOKEN
