version: "3.6"

services:
  app:
    image: sirius-lpa-frontend:latest
    build:
      context: ..
      dockerfile: ./docker/sirius-lpa-frontend/Dockerfile
    depends_on:
      - pact-stub
    ports: ["8888:8080"]
    environment:
      SIRIUS_URL: http://pact-stub:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080

  pact-stub:
    build: ./pact-stub
    environment:
      PACT_DIR: ./pacts
      PORT: 8080
    volumes:
      - ../pacts:/app/pacts

  puppeteer:
    build: ./puppeteer
    depends_on:
      - app
      - pact-stub
    environment:
      - LHCI_BUILD_CONTEXT__CURRENT_HASH=$GITHUB_SHA
      - LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG=ministryofjustice/opg-sirius-lpa-frontend
      - LHCI_GITHUB_APP_TOKEN
